In [0]:
simpleData = [(1,"Sagar","CSE","UP",80),(2,"Shivam","IT","MP",86),(3,"Muni","Mech","AP",70)]

columns = ["ID","StudentName","Department","City","Marks"]
df_1 = spark.createDataFrame(data = simpleData,schema = columns)
df_1.show()

+---+-----------+----------+----+-----+
| ID|StudentName|Department|City|Marks|
+---+-----------+----------+----+-----+
|  1|      Sagar|       CSE|  UP|   80|
|  2|     Shivam|        IT|  MP|   86|
|  3|       Muni|      Mech|  AP|   70|
+---+-----------+----------+----+-----+

In [0]:
simpleData1 = [(5,"Raj","CSE","HP"),(7,"Kunal","Mech","Rajasthan")]

columns = ["ID","StudentName","Department","City"]
df_2 = spark.createDataFrame(data = simpleData1,schema = columns)
df_2.show()

+---+-----------+----------+---------+
| ID|StudentName|Department|     City|
+---+-----------+----------+---------+
|  5|        Raj|       CSE|       HP|
|  7|      Kunal|      Mech|Rajasthan|
+---+-----------+----------+---------+

In [0]:
from pyspark.sql.functions import lit
# fill up missing value using lit command 
df_2 = df_2.withColumn("Marks",lit("null"))
df = df_1.union(df_2)
df.show()

+---+-----------+----------+---------+-----+
| ID|StudentName|Department|     City|Marks|
+---+-----------+----------+---------+-----+
|  1|      Sagar|       CSE|       UP|   80|
|  2|     Shivam|        IT|       MP|   86|
|  3|       Muni|      Mech|       AP|   70|
|  5|        Raj|       CSE|       HP| null|
|  7|      Kunal|      Mech|Rajasthan| null|
+---+-----------+----------+---------+-----+

In [0]:
input = "SaGar"
output = "sAgAr"

In [0]:
def convertcase(st):
    c=""
    for i in st:
        if ('a'<=i<='z'):
            c=c+i.upper()
        else:
            c=c+i.lower()
    return c

In [0]:
a = convertcase(input)
print(a)

sAgAR

In [0]:
from pyspark.sql.functions import col,udf
convertcase_df = udf(convertcase)
df.select(col("ID"),convertcase_df(col("StudentName")).alias("StudentName")).show()

+---+-----------+
| ID|StudentName|
+---+-----------+
|  1|      sAGAR|
|  2|     sHIVAM|
|  3|       mUNI|
|  5|        rAJ|
|  7|      kUNAL|
+---+-----------+

In [0]:
df.select(col("ID"),convertcase_df(col("StudentName")).alias("StudentName"),convertcase_df(col("City")).alias("City")).show()

+---+-----------+---------+
| ID|StudentName|     City|
+---+-----------+---------+
|  1|      sAGAR|       up|
|  2|     sHIVAM|       mp|
|  3|       mUNI|       ap|
|  5|        rAJ|       hp|
|  7|      kUNAL|rAJASTHAN|
+---+-----------+---------+

In [0]:
# Create a view or table with DataFrame

temp_table_name = "Sample_csv"

df.createOrReplaceTempView(temp_table_name)

In [0]:
%sql

/* Query the created temp table in a SQL cell */

select * from Sample_csv

ID,StudentName,Department,City,Marks
1,Sagar,CSE,UP,80
2,Shivam,IT,MP,86
3,Muni,Mech,AP,70
5,Raj,CSE,HP,null
7,Kunal,Mech,Rajasthan,null

In [0]:
spark.udf.register("convertcase_sql",convertcase)

Out[12]: <function __main__.convertcase(st)>

In [0]:
%sql

select *,convertcase_sql(StudentName) As StudentName from Sample_csv

ID,StudentName,Department,City,Marks,StudentName
1,Sagar,CSE,UP,80,sAGAR
2,Shivam,IT,MP,86,sHIVAM
3,Muni,Mech,AP,70,mUNI
5,Raj,CSE,HP,null,rAJ
7,Kunal,Mech,Rajasthan,null,kUNAL