In [0]:
sch = "ID int,Name String,Age int"
df = spark.readStream.option("header",True).schema(sch).csv('/FileStore/tables/student_database/')
display(df)

ID,Name,Age
1,Sagarendra,24
2,Shiva,23
3,Alexander,34
4,Kunal M,20
5,Kimkarde,12
1,Sagar1,24
2,Shivam1,23
3,Alex1,34
4,Kunal1,20
5,Kim1,12
1,Sagar,24
2,Shivam,23
3,Alex,34
4,Kunal,20
5,Kim,12

In [0]:
# append,complete and update modes of writestream command
df.writeStream.format('console').outputMode('append').start()

Out[2]: <pyspark.sql.streaming.StreamingQuery at 0x7f98b2b7eac0>

In [0]:
sch = "ID int,Name String,Age int"
df = spark.readStream.option("header",True).schema(sch).option("maxfilespertrigger",1).csv('/FileStore/tables/student_database/')
display(df)

ID,Name,Age
1,Sagar,24
2,Shivam,23
3,Alex,34
4,Kunal,20
5,Kim,12
1,Sagarendra,24
2,Shiva,23
3,Alexander,34
4,Kunal M,20
5,Kimkarde,12
1,Sagar1,24
2,Shivam1,23
3,Alex1,34
4,Kunal1,20
5,Kim1,12
1,Sagarendra,24
2,Shiva,23
3,Alexander,34
4,Kunal M,20
5,Kimkarde,12
1,Sagar1,24
2,Shivam1,23
3,Alex1,34
4,Kunal1,20
5,Kim1,12

In [0]:
df.writeStream.format('console').trigger(processingTime="10 seconds").outputMode('append').start()

Out[6]: <pyspark.sql.streaming.StreamingQuery at 0x7f98b2ba9040>